name: Release

on:
  push:
    branches:
      - main

jobs:
  alfarelease:
    name: Alfa release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm i

      - name: Create Alfa Release Pull Request or Publish to Artifactory
        id: changesets
        uses: changesets/action@v1
        with:
          title: Alfa release
          version: npx changeset pre enter alfa && npx changeset version
          commit: Alfa Version release
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.EXP_JFROG_TOKEN_READ_WRITE }}

      - name: Cleanup
        if: steps.changesets.outputs.published == 'true'
        run: |
          npx changeset pre exit
          git add .
          git commit -m "Exit prerelease mode"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


