name: Alfa-release

on: workflow_dispatch

jobs:
  alfarelease:
    name: Alfa release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm i

      - name: Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Alfa version
        id: changesets
        run: | 
          npx changeset pre enter alfa 
          npx changeset version 
          git add .
          git commit -m "alfa-release"

      - name: Alfa release publish
        id: alfa-release-publish
        run: | 
          npx changeset publish
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Cleanup
        run: |
          npx changeset pre exit
          git add .
          git commit -m "Exit alfa-release mode"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


